#!/bin/sh
#DEBHELPER#

set -e

# Compile GSettings schemas
if [ "$1" = "configure" ] && [ -d /usr/share/glib-2.0/schemas ]; then
    echo "Compiling GSettings schemas..."
    glib-compile-schemas /usr/share/glib-2.0/schemas
fi

exit 0